#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, Optional


ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from Caption_Gen import build_dense_expected_caption_pack, validate_scene_plan
from pipeline_runtime import get_selected_model, load_model_links


def _write_json(path: Path, payload: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build dense frame-range expected captions from scene-plan windows."
    )
    parser.add_argument(
        "--scene-plan",
        default="outputs/story/scene_plan.json",
        help="Path to scene plan JSON generated by LLM_MODEL.",
    )
    parser.add_argument(
        "--output",
        default="outputs/caption/dense_expected_video_captions.json",
        help="Path to output dense expected caption JSON.",
    )
    parser.add_argument(
        "--fps",
        type=int,
        default=24,
        help="Frames per second used by the video/caption pipeline.",
    )
    parser.add_argument(
        "--segment-length-frames",
        type=int,
        default=6,
        help="Number of frames per dense caption segment.",
    )
    parser.add_argument(
        "--overlap-frames",
        type=int,
        default=0,
        help="Frame overlap between consecutive segments.",
    )
    parser.add_argument(
        "--json-report",
        default=None,
        help="Optional machine-readable status report path.",
    )
    parser.add_argument(
        "--model-links",
        default="outputs/pipeline/model_links.json",
        help="Optional linked model manifest path.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    scene_plan_path = Path(args.scene_plan)
    output_path = Path(args.output)
    report_path: Optional[Path] = Path(args.json_report) if args.json_report else None
    model_links_path = Path(args.model_links)

    if not scene_plan_path.exists():
        payload = {
            "ok": False,
            "errors": [{"path": "scene_plan", "message": f"file not found: {scene_plan_path}"}],
        }
        if report_path:
            _write_json(report_path, payload)
        print(f"[ERROR] scene plan not found: {scene_plan_path}", file=sys.stderr)
        return 1

    try:
        scene_plan = json.loads(scene_plan_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        payload = {
            "ok": False,
            "errors": [{"path": "scene_plan", "message": f"invalid JSON: {exc}"}],
        }
        if report_path:
            _write_json(report_path, payload)
        print(f"[ERROR] invalid JSON in {scene_plan_path}: {exc}", file=sys.stderr)
        return 1

    errors = validate_scene_plan(scene_plan)
    if errors:
        payload = {"ok": False, "errors": errors}
        if report_path:
            _write_json(report_path, payload)
        print("[ERROR] scene plan validation failed:", file=sys.stderr)
        for err in errors:
            print(f"  - {err['path']}: {err['message']}", file=sys.stderr)
        return 1

    try:
        dense_pack = build_dense_expected_caption_pack(
            scene_plan,
            fps=args.fps,
            segment_length_frames=args.segment_length_frames,
            overlap_frames=args.overlap_frames,
        )
    except ValueError as exc:
        payload = {"ok": False, "errors": [{"path": "dense_caption_builder", "message": str(exc)}]}
        if report_path:
            _write_json(report_path, payload)
        print(f"[ERROR] dense caption build failed: {exc}", file=sys.stderr)
        return 1

    model_links = load_model_links(model_links_path)
    selected_caption_model = get_selected_model(model_links, "caption_gen")
    if selected_caption_model is not None:
        dense_pack.setdefault("runtime_models", {})["caption_gen"] = selected_caption_model

    _write_json(output_path, dense_pack)
    success = {
        "ok": True,
        "errors": [],
        "output": str(output_path),
        "story_id": dense_pack["story_id"],
        "total_windows": dense_pack["total_windows"],
        "total_segments": dense_pack["total_segments"],
        "fps": dense_pack["fps"],
        "segment_length_frames": dense_pack["segment_length_frames"],
        "overlap_frames": dense_pack["overlap_frames"],
    }
    if report_path:
        _write_json(report_path, success)

    print(
        f"[OK] dense expected captions generated: {output_path} "
        f"(story_id={dense_pack['story_id']}, windows={dense_pack['total_windows']}, "
        f"segments={dense_pack['total_segments']})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
